# Generated by Django 5.2.8 on 2025-11-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city_name",
                    models.CharField(max_length=100, verbose_name="Название города"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время запроса"
                    ),
                ),
                ("temperature", models.FloatField(verbose_name="Температура (°C)")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание погоды"),
                ),
                (
                    "humidity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Влажность (%)"
                    ),
                ),
                (
                    "wind_speed",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Скорость ветра (м/с)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос погоды",
                "verbose_name_plural": "Запросы погоды",
                "ordering": ["-timestamp"],
            },
        ),
    ]
