# Generated by Django 5.2.8 on 2025-11-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather_query", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherquery",
            name="from_cache",
            field=models.BooleanField(default=False, verbose_name="Из кэша"),
        ),
    ]
