# Generated by Django 5.2.8 on 2025-11-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather_query", "0002_weatherquery_from_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherquery",
            name="units",
            field=models.CharField(
                choices=[("metric", "°C"), ("imperial", "°F")],
                default="metric",
                max_length=10,
                verbose_name="Единицы измерения",
            ),
        ),
    ]
